### ISSUE TITLE
Select direct match file

### ISSUE THREAD

**Issue by astrauka** [astrauka/TestRSpec#1]
When switching between test and rspec, if there are two files with same name, then drop down is displayed. Add flag to directly jump to first match

**Comment by ksarunas** [comment]
👍

**Comment by astrauka** [comment]
> if there is an exact match then directly jump to that one. Otherwise show dropdown.

@ksarunas exactly

**Comment by astrauka** [comment]
@ksarunas https://github.com/astrauka/TestRSpec/commit/2cc4b482f5c0c60d94e0ab85d3c2f0918982508e
Created new tag https://github.com/astrauka/TestRSpec/releases/tag/v1.0.3
Package should update in a few hours

**Comment by ksarunas** [comment]
Great! Thanks 👍
