### ISSUE TITLE
Hide inline help with keyboard instead of mouse clicking the [x]

### ISSUE THREAD

**Issue by seanlerner** [astrauka/TestRSpec#10]
Hello, 

Thanks for developing this. It works well and setup was smooth.

Is it possible to hide the inline help using the keyboard (and without using the mouse to click the [x]) ?

Thanks,

Sean

**Comment by rpbaptist** [comment]
That would be very helpful. Could there also be a feature to not display this output in the code?

**Comment by rpbaptist** [comment]
I just figured out this is a new feature of Sublime Text and has nothing to do with this package.

**Comment by OlegSmelov** [comment]
Sublime seems to do this by default for all builds now:

https://www.sublimetext.com/blog/articles/sublime-text-3-build-3124

You can disable this by changing the `show_errors_inline` setting.
