### ISSUE TITLE
Not working on build 3126 ST3

### ISSUE THREAD

**Issue by Dania02525** [astrauka/TestRSpec#17]
Getting this error: 
```
TestRSpec: Running rspec
Traceback (most recent call last):
  File "/Users/myuseraccount/Library/Application Support/Sublime Text 3/Installed Packages/TestRSpec.sublime-package/plugin_helpers/utils.py", line 36, in __call__
KeyError: (<function Output.panel at 0x110d04560>, (), frozenset())
```

When attempting to run tests.  Settings file: 
```
{
  "rspec_add_to_path": "$HOME/.rbenv/shims"
}
```
ST3 build 3126. Installed add-ons: 
GitGutter
Rubocop
Boxy Theme
React Templates

Standard specfile location in /spec/filename_spec.rb and running MacOS Yosemite

**Comment by OlegSmelov** [comment]
Is there any more output? A full backtrace would be very helpful. 😄 

I think I've seen something like this right after installing this plugin, but I can't quite remember what I did.

**Comment by astrauka** [comment]
@Dania02525 could you try:
* restart Sublime
* if that does not help - remove and install TestRspec package

**Comment by Dania02525** [comment]
Resetting did it, thank you!
