### ISSUE TITLE
Run all specs?

### ISSUE THREAD

**Issue by dclausen** [astrauka/TestRSpec#19]
While running a specific spec and all specs in a file works, is it possible to run all specs?

**Comment by OlegSmelov** [comment]
There is no such command currently. I use terminal to run all specs.

**Comment by astrauka** [comment]
@dclausen running all specs works for small projects only. It is possible to add the command but I am not sure if there's much value in it.

**Comment by astrauka** [comment]
@dclausen can I close the issue?
