### ISSUE TITLE
Make plugin commands available in command palette

### ISSUE THREAD

**Issue by gediminas-zlatkus** [astrauka/TestRSpec#2]
TestRSpec commands can be invoked using keyboard shortcuts or menu:

<img width="311" alt="screen_shot_2016-04-27_at_13_43_51" src="https://cloud.githubusercontent.com/assets/10496443/14849880/250aaad6-0c7e-11e6-8b56-36a95264ddb8.png">

Which is great, but I'd suggest to also make them available in command palette (`cmd+shift+p`):

<img width="289" alt="screen_shot_2016-04-27_at_13_45_30" src="https://cloud.githubusercontent.com/assets/10496443/14849914/5fdd4768-0c7e-11e6-8d55-eb958ceb74da.png">

**Comment by astrauka** [comment]
:+1:

**Comment by astrauka** [comment]
Fixed in v1.0.4
