### ISSUE TITLE
Quickly navigate from `it_behaves_like` to `shared_example`

### ISSUE THREAD

**Issue by mhenrixon** [astrauka/TestRSpec#20]
Hi,

I have a feature request to be able to quickly navigate from `it_behaves_like` to corresponding definition of the `shareds_example`. 

I don't really do python but I could try and whip something up to solve the issue. The reason I am asking here is because I am using TestRSpec and felt like it might belong here. If @astrauka feels otherwise I will create my own plugin for this.

Thoughts?

**Comment by astrauka** [comment]
@mhenrixon sounds good :)
Please read http://engineering.vinted.com/2016/06/27/how-to-write-sublime-plugin/ on hints of how to write a sublime plugin. Sadly the developer experience is quite poor.
