### ISSUE TITLE
rails 5.1 and rspec 3.7

### ISSUE THREAD

**Issue by fabriziobertoglio1987** [astrauka/TestRSpec#27]
Hello,

I m using rails 5.1 and 

```
  * rspec-core (3.7.0)
  * rspec-expectations (3.7.0)
  * rspec-mocks (3.7.0)
  * rspec-rails (3.7.2)
  * rspec-support (3.7.0)
```

the following setting worked for me

`  "check_for_spring": false,`

The plugin it's great and works amazing

**Comment by astrauka** [comment]
Hello @fabriziobertoglio1987 ,
I did not understand your comment, is there any issue or is everything working as expected?

**Comment by fabriziobertoglio1987** [comment]
@astrauka yes. When setting `"check_for_spring": false` works, because I run test with `bundle exec rspec spec` and I do not use `spring`

**Comment by astrauka** [comment]
Great :)

**Comment by OlegSmelov** [comment]
To use `rspec` with `spring`, [spring-commands-rspec](https://github.com/jonleighton/spring-commands-rspec) is required. cc @fabriziobertoglio1987

I guess the real bug report there is that `check_for_spring` doesn't quite work right, we might need to check for both `spring` and `spring-commands-rspec` in the Gemfile.
