### ISSUE TITLE
Unwanted escape characters in output panel

### ISSUE THREAD

**Issue by tommarshall** [astrauka/TestRSpec#30]
Firstly, thanks for creating this plugin. I've only just discovered it, but it's going to save so much time 🙌 

I'm getting some unwanted escape characters at the start out the output:

![image](https://user-images.githubusercontent.com/1125251/36727902-d2d5855c-1bb6-11e8-8a6a-ebeb40c08f6f.png)

I get the same character string on all output that I've seen so far.

---

macOS High Sierra 10.13.2 (17C88)
Sublime Text 3.0 Build 3143

`TestRSpec.sublime-settings`:

```
{
  "rspec_command": "docker-compose exec -T web rspec",
  "check_for_rbenv": false,
  "check_for_rvm": false,
  "check_for_system_ruby": false,
  "check_for_bundler": false,
  "check_for_spring": false,
}
```

I've tested without the user setting overrides and I'm getting the same issue, so I don't believe the config, or that it's running `rspec` within a docker container to be relevant.

**Comment by OlegSmelov** [comment]
I used the exact same config you provided, but I could not reproduce with an empty Rails 5.1 project inside a Docker container.  😕 

![rspec](https://user-images.githubusercontent.com/544537/36913073-6749f53c-1e51-11e8-995c-2e15d1bac8ce.png)

@tommarshall Can you provide output of this command?

```
docker-compose exec -T web rspec spec/models/user_spec.rb:15 | hexdump -C | head -n 3
```

We'd then know what's being outputted exactly.

**Comment by tommarshall** [comment]
Hi @OlegSmelov, thanks for taking a look at this.

If I add the piped `hexdump` and `head` to the `rspec_command` in the config.

```
{
  "rspec_command": "docker-compose exec -T web rspec spec/models/user_spec.rb:15 | hexdump -C | head -n 3",
...
}
```

I get the following when running for the whole file:

![image](https://user-images.githubusercontent.com/1125251/36944777-c8b75ea0-1f9a-11e8-80ec-8c5f3038c8f0.png)

And the following when I run for a single line in a file:

![image](https://user-images.githubusercontent.com/1125251/36944796-2453b312-1f9b-11e8-9c06-02386b1490b2.png)

I run directly in the terminal I get the actual output from `hexdump`, but I'm not seeing the escape characters there, so I don't believe this to be helpful.

```
$ docker-compose exec -T web rspec spec/models/user_spec.rb:15 | hexdump -C | head -n 3
00000000  52 75 6e 20 6f 70 74 69  6f 6e 73 3a 20 69 6e 63  |Run options: inc|
00000010  6c 75 64 65 20 7b 3a 6c  6f 63 61 74 69 6f 6e 73  |lude {:locations|
00000020  3d 3e 7b 22 2e 2f 73 70  65 63 2f 6d 6f 64 65 6c  |=>{"./spec/model|
```

**Comment by OlegSmelov** [comment]
@tommarshall 

This config

```
"rspec_command": "docker-compose exec -T web rspec spec/models/user_spec.rb:15 | hexdump -C | head -n 3",
```

doesn't quite work because the extension appends the file name to the command, and then `head` just reads first 3 lines of `user.rb`. What we've learned though is that those escape characters are not outputted by `rspec` or `docker-compose`, so it must be your shell that does it.

Can you run this in command in Sublime console (ctrl+\`)?

```
view.window().run_command("exec", { "shell_cmd": "echo $SHELL" })
```

If my guess is correct, you should see the same escape characters and then the path to your shell.

**Comment by OlegSmelov** [comment]
The ultimate test is running this directly in the terminal:
 
`bash -lc "" | hexdump -C`

If you see those characters, this means you have something in `~/.bash_profile` (or some other file) that outputs them.

**Comment by tommarshall** [comment]
Thanks @OlegSmelov.

Using `bash -lc "" | hexdump -C` I was able to track the issue down to my prompt, which is included my `~/.bash_profile`.

FWIW, and in case somebody else comes across this issue, the actual characters:

```
$ bash -lc "" | hexdump -C
00000000  1b 28 42 1b 5b 6d                                 |.(B.[m|
00000006
```

Were coming from `tput sgr0`, which is being used a customised version of [Addy Osmani's prompt](https://github.com/addyosmani/dotfiles/blob/5d583a9/.bash_prompt#L11).
