### ISSUE TITLE
Hide output panel

### ISSUE THREAD

**Issue by zinga666** [astrauka/TestRSpec#33]
Hi,

am I missing something or is it not possible to hide the output panel (using the keyboard)?

Installed TestRSpec on Sublime Text 3.0 Build 3143 on Linux (and being a newbie to Sublime).

**Comment by OlegSmelov** [comment]
Have you tried escape?

**Comment by zinga666** [comment]
Lol, just figured it out by myself too... Thx for the quick answer though!
