### ISSUE TITLE
Default commands override

### ISSUE THREAD

**Issue by Shuiei** [astrauka/TestRSpec#35]
It seems that `Super + Shift + T` override the default shortcut which reopens the previously closed file. Even after setting my custom user input the shortcut is still overridden. (On MAC).

Is there any way to completely override YOUR default settings for the package? It would be really cool because this package is a big time saver ^^

Thanks.

**Comment by OlegSmelov** [comment]
Just in case, what did you set your custom shortcut to? I'll try to reproduce this.

**Comment by Shuiei** [comment]
I replaced all `super + shift` by `control + super` by copy/past the default config into my custom config.

**Comment by smanolloff** [comment]
@Shuiei jfyi, as a workaround you can completely override the key bindings via Package Control -> Open Resource -> TestRspec and editing the keymap from there.
