### ISSUE TITLE
Support spaces in paths: Windows compatibility

### ISSUE THREAD

**Issue by edthamm** [astrauka/TestRSpec#36]
Hi!

First of all thanks for this package your work helps us a lot.
We noticed a regression introduced with version 1.0.8 details see below

|Title|Details|
|---|---|
|**Environments**| <ul><li>Microsoft Windows [Version 10.0.16299.431] cmd.exe</li><li>Windows 8 cmd.exe</li><ul>|
|**Steps to reproduce**|<ol><li>Open a spec file in sublime</li><li>Use the "Test Current File" command</li></ol>|
|**Expected Result**| Running tests via a TestRSpec command runs the tests and reports the results |
|**Current Result**| Test are not executed and an error is displayed. Error message in cmd: The filename, directory name, or volume label syntax is incorrect. |
|**Initial Analysis**| Windows cmd does not tolerate single quoted strings as input for the cd command. |
|**Most likely Culprit**| #32 |

Switching to powershell is not an option as powershell does not support command chaining via ```&&``` and using WSL also does not solve our problems as most of us still use Windows 8.

**Comment by astrauka** [comment]
@edthamm thank you for such a cool issue description!
Would you like making a PR with the fix?

**Comment by OlegSmelov** [comment]
I'm really surprised this plugin used to work on Windows. The problem is that none of us uses Windows and getting a Windows machine up and running and setting up a proper development environment will take a while.

Input is welcome if you know how to fix this without breaking *nix compatibility. 😄

**Comment by edthamm** [comment]
Hi!

Sorry for taking so long to reply.
It's currently quite busy at work.
I will cook up a PR asap, most likely next week.

Testing it against multiple OS's won't be a problem. Windows is more of a workplace thing for me and I personally prefer working on *nix systems.

Well, anyways I was thinking about using sys or platform to determine the underlying os and then going from there.
I have not had a look at if or how I can achieve this with shlex. But there certainly is some reasonable way to do this. I.e. there is most likely a multi-platform escaping mechanism in the standard library.

**Comment by edthamm** [comment]
Just as an update: I finally came around to drafting a fix for the issue.
Once I am done testing it on both Windows and Linux I'll create a pull request for review.

**Comment by edthamm** [comment]
See #37 For suggested fix. If someone could test this on a Mac I would be very obliged. I don't have one so I can not do that.
