### ISSUE TITLE
Open request spec for controller

### ISSUE THREAD

**Issue by printercu** [astrauka/TestRSpec#38]
Hi, and thanks for the plugin! :)

Is it possible to open files from spec/requests for controller classes? Now it creates controller spec when switching to spec from controller while request spec is already present.

**Comment by OlegSmelov** [comment]
What is the spec file called? Does it match the name of the controller?

**Comment by printercu** [comment]
Yep. I have `app/controllers/admin/users_controller.rb` and `spec/requests/admin/users_spec.rb`. When I hit `super+.` in controller it shows message that spec file is not found. When I hit `super+alt+c` it creates `spec/controllers/admin/users_controller_spec.rb`.

I've checked that having `spec/requests/admin/users_controller_spec.rb` resolves problem. But it does not follow naming conventions. It's also not possible to create missing request spec files instead of controller specs.

**Comment by OlegSmelov** [comment]
I don't personally use request specs, but from what I gather it can be tricky to match controllers and request specs, as there is no strict connection between them.

As I imagine, you could have `spec/requests/authentication_spec.rb` that's tied to `app/controllers/users_controller.rb`, but it's not possible to infer the connection from file names alone.

However, for this case we could have these mappings:

1. `app/controllers/<a>/<b>_controller.rb` <-> `spec/controllers/<a>/<b>_controller_spec.rb`
2. `app/controllers/<a>/<b>_controller.rb` <-> `spec/requests/<a>/<b>_spec.rb`

The first one is already implemented. Maybe you're interested in implementing the second one? 😄

**Comment by printercu** [comment]
Thanks! I'll check the code soon.

**Comment by printercu** [comment]
Seems like it's not evident for me how to implement this, and I can't work on this now.

Should I close the issue?

**Comment by OlegSmelov** [comment]
If anyone else needs this feature and has the time to implement it, pull requests are welcome. 👍 

Closing because it's not a major issue.
