### ISSUE TITLE
No Color in Output Panel 

### ISSUE THREAD

**Issue by jmcbri** [astrauka/TestRSpec#39]
I don't get colored output. Should I fool around with the theme?  Any hints would be appreciated.

**Comment by OlegSmelov** [comment]
Can you provide a screenshot and describe how you imagine output should look like?

**Comment by jmcbri** [comment]
Thanks for the quick response Oleg.  In the animated gif that is part of the README.MD, the output is "colored output". Specifically, for example, the "1 example, 0 failures" is a lovely PASSING green. 

When I run tests the same manner, there is no color at all.  See attached/below. 
![image](https://user-images.githubusercontent.com/118145/52024451-df50fb00-24ce-11e9-97e7-5e3399fad48b.png)

**Comment by OlegSmelov** [comment]
Not sure what's happening here. The output panel should have a `TestConsole` syntax (bundled with the plugin), which matches things like "1 example, 0 failures" and colors them.

Here are some things to check:

* Have you by any chance overriden `panel_settings` key in plugin's configuration?
* Open the output panel, click in the middle of the word "example" and press `Ctrl+Alt+Shift+P`, it should bring up this little window:

![screenshot 2019-01-31 at 12 44 52](https://user-images.githubusercontent.com/544537/52049331-2d5d1180-2556-11e9-8605-79dc12f3d506.png)

**Comment by jmcbri** [comment]
Yes, I had overridden panel_setting to try to fix it didn't have any effect that I could see. I removed all the settings.

When I click in the' example' I get 'source.loghighlight'

**Comment by jmcbri** [comment]
One last thing ;) I didn't think worth mentioning, but I had to add the below to me setting to get the plugin to work:
{
  "rspec_add_to_path": "$HOME/.rbenv/shims"
}

**Comment by OlegSmelov** [comment]
@jmcbri Do you have this plugin installed? https://packagecontrol.io/packages/Log%20Highlight

Judging by `source.loghighlight`, its syntax is applied to the output panel instead of TestRSpec's.

> Can I send you a beer of something?

No need, thanks. 😄 

> I had to add the below to me setting to get the plugin to work

This is mentioned here: https://github.com/astrauka/TestRSpec#ruby-not-found

**Comment by jmcbri** [comment]
Removing that package did it!  Wonderful green highlighting now! Thanks for your patience. I didn't even realize I had the other package installed.

**Comment by OlegSmelov** [comment]
I'm glad it worked!
