### ISSUE TITLE
Keybinding for `copy rspec command for current line`

### ISSUE THREAD

**Issue by alexanderadam** [astrauka/TestRSpec#42]
Sometimes it would be nice to just copy the command of the current spec (i.e. when you want to debug your application within a 'real' terminal).

So similar what `test_current_line` would do but instead of executing the command, it should be copied to the clipboard.

PS: thank you for your work! :+1:

**Comment by OlegSmelov** [comment]
To avoid having multiple shortcuts, I think we can create a `copy_last_spec` command, similar to what `run_last_spec` (`cmd/super+shift+e`) does, but instead of running the last command again, it would copy the command to clipboard. Should be doable.

**Comment by alexanderadam** [comment]
wow, thank you for your insanely fast response! :wink: 

So could I copy the command without having to run a spec first? :thinking:

**Comment by OlegSmelov** [comment]
Not without running it first, no. Is that a problem?

If it is, we could go for two separate new commands then.

**Comment by alexanderadam** [comment]
I probably wouldn't execute the command in such cases but it wouldn't be too much of a problem.
I guess I could just type those keybindings just shortly after each other. It would help me either way, as long as there's a possibility to just copy and paste it in a terminal. :wink:

**Comment by OlegSmelov** [comment]
Let's add separate keybindings then, that should cover more use cases.

**Comment by OlegSmelov** [comment]
v1.0.10 is going to be released soon which has a command to copy the last RSpec command (`cmd/super+shift+,`).

**Comment by Bajena** [comment]
Thanks for quick review @OlegSmelov! Btw, this new command is indeed pretty useful :)
