### ISSUE TITLE
Could not find 'bundler'

### ISSUE THREAD

**Issue by jro31** [astrauka/TestRSpec#48]
I'm working on a new project and have just installed TestRSpec in Sublime 3.2.2 via Package Control. Whenever I try to run a spec I get the following error:
```
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': Could not find 'bundler' (2.1.2) required by your /Users/jethrowilliams/Google Drive/code/Plant-as-Usual-2/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.1.2`
  from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
  from /usr/bin/bundle:23:in `<main>'
[Finished in 0.3s with exit code 1]
[shell_cmd: ( cd '/Users/jethrowilliams/Google Drive/code/Plant-as-Usual-2' && /usr/bin/env ruby -S bundle exec spring rspec spec/models/recipe_spec.rb)]
[dir: /Users/jethrowilliams/Google Drive/code/Plant-as-Usual-2]
[path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:./bin:./node_modules/.bin:/anaconda3/bin:/Users/jethrowilliams/anaconda3/bin:/Users/jethrowilliams/.rbenv/shims:/Users/jethrowilliams/.rbenv/bin:/usr/local/sbin]
```
I've tried running `bundle update` and `bundle update --bundler`. I've uninstalled and reinstalled TestRSpec, restarted Sublime. The problem still persists.

When I run `gem list bundler` I get:
```
gem list bundler

*** LOCAL GEMS ***

bundler (2.1.2, 2.0.2, default: 1.17.2)
```
Any other ideas on how to fix this issue?

**Comment by OlegSmelov** [comment]
Judging by the path in logs, the plugin is using system Ruby.

What do you use for Ruby version management? The likely cause is that the version manager is not configured to load in `~/.bashrc`. Even if you don't use Bash as the default shell, it's still necessary to make it work in Bash.

**Comment by jro31** [comment]
Ah, that might be it. I use Rbenv and Zsh.

**Comment by andersklenke** [comment]
Thanks @OlegSmelov . I ran into the same issue, and it fixed it for me :+1:

**Comment by jro31** [comment]
Thanks @OlegSmelov, finally had the time to sit-down today and figure-out exactly how to do that. It's working fine now.

To anyone else struggling who finds this thread, what I did to fix it (on Mac, using Rbenv) was open the `~/.bash_profile` file in a text editor. That can either be in Terminal (as [here](https://stackoverflow.com/a/23504622/2475306)) or through Finder, going `Users -> yourname -> .bash_profile` (going through finder you need to show hidden files. You can do this by pressing `command + shift + .`).

Then paste the line `eval "$(rbenv init -)"` to the bottom of the file (this line is given to you by typing `rbenv init` in Terminal).

Save it, restart Sublime, and for me the issue was fixed.

**Comment by ellmo** [comment]
Hey guys, need help with this. Fixing `.bash_profile` did not help.

```
SublimeLinter: WARNING: rubocop output:
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': Could not find 'bundler' (2.2.26) required by your /Users/.../Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.2.26`
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
	from /usr/bin/bundle:23:in `<main>'
```

And this is my `SublimeLinter.sublime-settings`:

```json
// SublimeLinter Settings - User
{
  "linters":{
    "rubocop":{
      "use_bundle_exec": true,
    }
  },
  "paths": {
        "linux": [],
        "osx": [
            "~/.rbenv/shims"
        ],
        "windows": []
    }
}
```

I'm going absolutely crazy

**Comment by OlegSmelov** [comment]
@ellmo It looks like you're trying to set up SublimeLinter. TestRSpec and SublimeLinter are unrelated plugins.
